export const CHARLATAN_TOPICS = {
  'Olympic sports': [
    'Athletics',
    'Basketball',
    'Boxing',
    'Canoeing',
    'Cycling',
    'Diving',
    'Equestrian',
    'Fencing',
    'Gymnastics',
    'Handball',
    'Hockey',
    'Judo',
    'Modern Pentathlon',
    'Rowing',
    'Sailing',
    'Shooting',
    'Swimming',
    'Table Tennis',
    'Taekwondo',
    'Tennis',
    'Weightlifting',
  ],

  'Zoo animals': [
    'Lion',
    'Tiger',
    'Gorilla',
    'Elephant',
    'Leopard',
    'Panda',
    'Kangaroo',
    'Giraffe',
    'Zebra',
    'Hippopotamus',
    'Monkey',
    'Rhinoceros',
    'Bear',
    'Kookaburra',
    'Flamingo',
    'Koala',
    'Ostrich',
    'Penguin',
    'Seal',
    'Snake',
  ],

  'Modern inventions': [
    'Smartphone',
    'Laptop',
    'Tablet',
    'Smart Watch',
    'Television',
    'Gaming Console',
    'Drones',
    'Virtual Reality Headset',
    'Smart Home Devices',
    'Fitness Tracker',
    'Bluetooth Speaker',
    'Wireless Earbuds',
    'Camera',
    'Electric Car',
    'Smart Thermostat',
    'Smart Lock',
    'Wireless Charger',
    '3D Printer',
    'Robot Vacuum',
    'Smart Scale',
  ],

  'House pets': [
    'Dog',
    'Cat',
    'Fish',
    'Bird',
    'Hamster',
    'Rabbit',
    'Guinea Pig',
    'Turtle',
    'Chinchilla',
    'Ferret',
    'Snake',
    'Lizard',
    'Tarantula',
    'Hermit Crab',
    'Rat',
    'Mice',
    'Gerbil',
    'Sugar Glider',
    'Bearded Dragon',
    'Iguana',
  ],

  Landmarks: [
    'Eiffel Tower',
    'Great Wall of China',
    'Big Ben',
    'Statue of Liberty',
    'Taj Mahal',
    'Pyramids of Giza',
    'Stonehenge',
    'Colosseum',
    'Christ the Redeemer',
    'Mount Everest',
    'Machu Picchu',
    'Sistine Chapel',
    'Hagia Sophia',
    'Sydney Opera House',
    'St. Petersburg Palace',
    'Angkor Wat',
    'Petra',
    'Leaning Tower of Pisa',
    'Chichen Itza',
    'Notre Dame Cathedral',
  ],

  fruits: [
    'Apple',
    'Banana',
    'Orange',
    'Strawberry',
    'Grape',
    'Mango',
    'Watermelon',
    'Pineapple',
    'Peach',
    'Blueberry',
    'Raspberry',
    'Blackberry',
    'Cherry',
    'Kiwi',
    'Lemon',
    'Lime',
    'Pomegranate',
    'Melon',
    'Plum',
    'Apricot',
  ],

  vegetables: [
    'Tomato',
    'Carrot',
    'Potato',
    'Lettuce',
    'Cucumber',
    'Onion',
    'Garlic',
    'Broccoli',
    'Bell Pepper',
    'Mushroom',
    'Spinach',
    'Cauliflower',
    'Peas',
    'Corn',
    'Zucchini',
    'Asparagus',
    'Eggplant',
    'Green Bean',
    'Artichoke',
    'Radish',
  ],

  waitingPlaces: [
    'Amusement Park Ride',
    'Movie Theater',
    'Airport Security',
    'Concert Venue',
    'Supermarket',
    'Post Office',
    'Banking Institution',
    'Government Office',
    'Fast Food Restaurant',
    'Coffee Shop',
    "Doctor's Office",
    'Hospital Emergency Room',
    'DMV',
    'Department Store',
    'Ikea',
    'School Registration',
    'Disney World',
    'Museum Admission',
    'Theme Park Entrance',
    'Stadium Concession Stand',
  ],

  historicalFigures: [
    'George Washington',
    'Abraham Lincoln',
    'Martin Luther King Jr.',
    'Winston Churchill',
    'Nelson Mandela',
    'Alexander the Great',
    ' Julius Caesar',
    'Christopher Columbus',
    'Napoleon Bonaparte',
    'Queen Elizabeth II',
    'Mahatma Gandhi',
    'Genghis Khan',
    'Leonardo da Vinci',
    'Isaac Newton',
    'Albert Einstein',
    'Galileo Galilei',
    'Marie Curie',
    'Charles Darwin',
    'Louis Pasteur',
    'Adolf Hitler',
  ],

  lotterySpending: [
    'New House',
    'Luxury Car',
    'Vacation Home',
    'Private Jet',
    'Yacht',
    'Exotic Vacation',
    'Investment Portfolio',
    'Retirement Fund',
    'Philanthropy',
    'Starting a Business',
    'College Fund for Children/Grandchildren',
    'Personal Spa Treatments',
    'Art Collection',
    'Jewelry',
    'Wine Collection',
    'Classic Car Collection',
    'Private Island',
    'Sports Team Ownership',
    'Live-In Chef',
    'Private Concert with Favorite Artist',
  ],

  foodsWithKetchup: [
    'French Fries',
    'Burger',
    'Hot Dog',
    'Grilled Cheese',
    'Fried Chicken',
    'Eggs',

    'Baked Beans',
    'Grilled Pork Chops',
    'Roasted Potatoes',
    'Pork Sausages',
    'Grilled Steak',
    'Barbecue Ribs',
    'Meatballs',
    'Veggie Burgers',
  ],

  popularBookSeries: [
    'Harry Potter',
    'The Hunger Games',
    'Twilight',
    'The Lord of the Rings',
    'Percy Jackson and the Olympians',
    'The Hobbit',
    'The Diary of a Wimpy Kid',
    'The Mortal Instruments',
    'The Fault in Our Stars',
    'Divergent',
    'The Maze Runner',
    'The Inheritance Cycle',
    'The Giver',
    'To Kill a Mockingbird',
    'The Chronicles of Narnia',
    'Little Women',
    "Charlotte's Web",
    'Where the Wild Things Are',
    'The Giving Tree',
    'Goodnight Moon',
  ],

  whiteGoods: [
    'Refrigerator',
    'Dishwasher',
    'Washing Machine',
    'Dryer',
    'Stove/Oven',
    'Microwave',
    'Freezer',
    'Trash Compactor',
    'Vacuum Cleaner',
    'Blender',
    'Food Processor',
    'Toaster',
    'Coffee Maker',
    'Air Conditioner',
    'Dehumidifier',
    'Fan',
    'Heater',
    'Air Purifier',
    'Water Cooler',
    'Slow Cooker',
  ],

  nintendoGames: [
    'Super Mario Bros.',
    'The Legend of Zelda',
    'Donkey Kong',
    'Metroid',
    'Kirby',
    'Pokemon',
    'Mario Kart',
    'Animal Crossing',
    'Super Smash Bros.',
    'Star Fox',
    'F-Zero',
    'Fire Emblem',
    'EarthBound',
    'Pikmin',
    'WarioWare',
    'The Legend of Zelda: Breath of the Wild',
    'Mario Party',
    'Splatoon',
  ],

  playstationGames: [
    'Gran Turismo',
    'Tekken',
    'Final Fantasy',
    'Metal Gear Solid',
    'Resident Evil',
    'Crash Bandicoot',
    'Spyro the Dragon',
    'Jak and Daxter',
    'God of War',
    'The Last of Us',
    'Uncharted',
    'Ratchet & Clank',
    'Grand Theft Auto',
    'LittleBigPlanet',
    'Infamous',
    'Shadow of the Colossus',
    'Bloodborne',
    'Spider-Man',
    'Horizon Zero Dawn',
    "Demon's Souls",
  ],

  musicalInstruments: [
    'Piano',
    'Guitar',
    'Drums',
    'Violin',
    'Saxophone',
    'Trumpet',
    'Flute',
    'Bass',
    'Cello',
    'Clarinet',
    'Ukulele',
    'Banjo',
    'Mandolin',
    'Harmonica',
    'Accordion',
    'Trombone',
    'Maracas',
    'Tambourine',
  ],

  famousCities: [
    'London',
    'Paris',
    'New York City',
    'Tokyo',
    'Beijing',
    'Rome',
    'Berlin',
    'Madrid',
    'Moscow',
    'Istanbul',
    'Dubai',
    'Shanghai',
    'Sydney',
    'Los Angeles',
    'Hong Kong',
    'Singapore',
    'Barcelona',
    'Vienna',
    'Amsterdam',
    'Seoul',
  ],
};
