export const CHARLATAN_TOPICS = {
  'Olympic Sports': [
    'Athletics',
    'Basketball',
    'Boxing',
    'Canoeing',
    'Cycling',
    'Diving',
    'Equestrian',
    'Fencing',
    'Gymnastics',
    'Handball',
    'Hockey',
    'Judo',
    'Modern Pentathlon',
    'Rowing',
    'Sailing',
    'Shooting',
    'Swimming',
    'Table Tennis',
    'Taekwondo',
    'Tennis',
    'Weightlifting',
  ],
};
