const VOTE_QUESTIONS = [
  'needs a hug',
  'is thinking about sausage right now',
  'is thinking about a unicorn right now',
  'is up at 7am on a Sunday',
  'would eat off the floor without thinking twice',
  'got too much Red Bull as a child',
  'has never experienced true anger',
  'thinks they could take on a lion with their bare hands',
  'is always overdressed',
  'can be a bit of a pretentious snob',
  'is a bit of a perfectionist',
  'would ask to speak to the manager',
  'would happily listen to one song for the rest of their life',
  'is a turtle',
  'will still just not get it in 10 years',
  'could be the boss',
  'has the most misunderstood humour',
  'will be totally different in 10 minutes',
  'should be sent to a distant planet',
  'has a secret treasure chest',
  'gives awful hugs',
  'gives great hugs',
  'would you never want as your backup if shit went down',
  'would try to fix the titanic with super glue',
  'would make a good ninja',
  'should we all hug right now',
  'would bring a knife to a fistfight',
  'never has an off day',
  'has too many secrets',
  'looks different to their personality',
  'will still be there for us 10 years',
  'thinks they are a professional athlete',
  'would make a good priest',
  'knows all the words to every ABBA song',
  'needs to see a fashion guru',
  'would you like to go club with',
  'is harbouring negative feelings',
  'is always underdressed',
  'is ready to shake things up',
  'would make a great surfer',
  "didn't get enough discipline as a child",
  'is going to complain at a restaurant',
  'is the one making silly suggestions in meetings',
  'would you like to go on a road trip with',
  "isn't hungry but is still ordering for two",
  'needs to be slapped out of it',
  'thinks they are good looking',
  'reckons they are an artist',
  'will lie to get themselves out of any situation',
  'needs to take a chill pill',
  'is hiding someone in their basement',
  'is hiding their true intelligence',
  'would make a good referee',
  'has delusions of greatness',
  'is still hungover from last night',
  'knows the meaning of life',
  'deserves a high five',
  'needs a shot of tequila',
  'thinks they are the boss',
  'eats too much avocado',
  'does all their shopping online',
  'would make a great public speaker',
  'would make a great therapist',
  'has got moves on the dance floor',
  'is unreasonably cheerful',
  'is a smooth talker',
  "doesn't know their true power",
  'needs to wake up',
  'would make a good negotiator',
  'believes in aliens',
  'is waiting for the right time to poison everyone',
  'eats pizza, crust first',
  'is really a vampire',
  'still gets Happy Meals from McDonalds',
  'gets a nosebleed if they walk too fast',
  'needs a few years in prison',
  'needs to get a haircut',
  'has a bad habit of not taking their medication',
  'has the wildest dreams',
  'is thinking about fairies right now',
  'will thrive in a zombie apocalypse',
  'is really a scientologist',
  'is going to live long enough to see themselves become the villain',
  'is most likely to be a spy',
  'will we still remember in 20-years time',
  'is planning their escape',
  'should narrate a nature documentary',
  `do you want as your "hype man"`,
  'is always the bad cop',
  'is always the good cop',
  'is visiting us from the future',
  'still believes in Santa',
  'will we send when the gods demand a sacrifice',
  'makes us laugh unintentionally',
  'watches too much Netflix',
  `would make a good farmer`,
  `drives a tractor`,
  `is definitely a morning person`,
  `is going to be famous`,
  `watches Home Alone in the summer`,
  `has a podcast`,
  `would rather get lost than ask for directions`,
  `cries during movies`,
  `is most likely to start a food fight`,
  `will betray you when you least expect it`,
  `is giving you dodgy advice`,
  `makes you feel warm and cuddly`,
  `drives too fast`,
  `was spoilt as a child`,
  `knows the real truth`,
  `would make a good car salesman`,
  `has 3 nipples`,
  `has the best pornstar name`,
  `is still searching for freedom`,
  `is going to be a great chef`,
  `is going to leave this world on a horse`,
  `uses a lot of sarcasm`,
  `has to be at every party`,
  `would make a great mix playlist`,
  `is going to leave us`,
  `pretends not to know you`,
  `makes you think`,
  `likes bad TV`,
  `should be a poet`,
  `loves gardening`,
  `is too real for this world`,
  `would make a good sex therapist`,
  `is going to write the next Bond movie`,
  `is shy around new people`,
  `is intimidated by life`,
  `loves catching bad guys`,
  `loves to drive fast cars`,
  `would make a great neighbour`,
  `uses an axe as a doorstop`,
  `shy of everyone and in love with nobody`,
  `digs holes`,
  `talks in their sleep`,
  `is a world class karaoke singer`,
  `never loses a fight`,
  `loves to scream`,
  `makes the best spaghetti and meatballs`,
  `runs a pet adoption centre`,
  `is a hippie at heart`,
  `is trying to live forever`,
  `cries at the hairdresser every time they cut it too short`,
  `can never say no`,
  `says they're vegan but buys burgers`,
  `has a librarian as a parent`,
  `needs an advice from their friend`,
  `cannot stand stupid people`,
  `would be the first person to shout at you when you drop your phone`,
  `would never let you get away with anything`,
  `is trying to make a movie about their life`,
  `is feeling something`,
  `has all the self control of a baby`,
  `hates reality`,
  `dreads mowing the lawn`,
  `would love being famous`,
  `would be the first one to run away with you`,
  `is going to get eaten by a bear`,
  `will laugh at your sadness`,
  `loves trashy television`,
  `loves to talk about themselves in third person`,
  `cries in front of your house every time they leave`,
  `hates wearing clothes`,
  `loves the colour purple`,
  `constantly trying to fix something or someone that isn't broken`,
  `is too trusting`,
  `wants you to dance for them and keeps saying that there's no better time than now`,
  `is convinced they are the one`,
  `would put hot sauce in your iced tea`,
  `blames everything on a conspiracy`,
  `has an imaginary friend`,
  `would spend one night a week at your place`,
  'sings loudly to songs only they know the words to',
  'makes bizarre noises in their sleep',
  'is addicted to shopping at garage sales',
  'gets lost easily and calls for directions often',
  "never stops telling jokes, even if they're not funny",
  'insists on giving everyone a nickname',
  'is terrible at remembering names',
  'always loses their keys',
  'carries a lucky charm everywhere they go',
  'talks to plants as if they were people',
  'is convinced aliens exist and will one day take over the world',
  'loves to play dress up and wear wacky outfits',
  'says everything twice for good luck',
  'never knows what to wear and changes outfits multiple times a day',
  'thinks carrots are evil and refuses to eat them',
  'always carries around a rubber chicken for good luck',
  "talks to inanimate objects as if they're alive",
  'has an obsession with collecting bottle caps',
  "thinks cheese is the answer to all life's problems",
  'can only communicate in rhyming couplets',
  'thinks all technology is controlled by robots',
  'insists on wearing mismatched socks on purpose',
  'collects leaves from every tree they pass',
  'tries to start a conga line wherever they go',
  'follows strangers without them noticing',
  'has a creepy laugh that sends shivers down your spine',
  'stares at people with a blank expression for long periods of time',
  "makes eerie and unsettling statements that don't make sense.",
  'winks at you constantly',
  'talks in a seductive tone',
  'brushes against you frequently',
  'smiles at you in a suggestive manner',
  'could successfuly flirt with a lampost',

  'has named their computer after a famous person',
  'can write code faster than they can text',
  'knows every keyboard shortcut in existence',
  'has a favorite hex color code',
  'thinks HTML stands for "How To Meet Ladies"',
  'would choose a lifetime supply of coffee over a new car',

  'believes "Law and Order" is a documentary series',
  'has a personal objection to losing any argument',
  'thinks they could defend a sandwich in court',

  'prescribes laughter as the best medicine',
  'has diagnosed their own fictional medical condition',
  'believes stethoscopes are the ultimate fashion accessory',

  'considers red pens a personal collection',
  `has a secret grading scale for students' doodles`,
  'believes they have a PhD in "classroom management"',

  'thinks the best ingredient is a pinch of love',
  'believes they can cook better than Gordon Ramsay',
  'has an ongoing rivalry with their kitchen appliances',

  'has practiced their Oscar acceptance speech in the mirror',
  'believes they were born to play the role of a talking animal',
  'has a secret talent for dramatic monologues in the shower',

  'is convinced they can solve any problem with a spreadsheet',
  'believes tax season is the most wonderful time of the year',
  'thinks calculators are an essential part of their wardrobe',

  'has designed their dream house on a napkin',
  'believes they can create a masterpiece using only Legos',
  'considers blueprints as their personal coloring books',

  'can turn any object into a musical instrument',
  'believes they are the reincarnation of a famous composer',
  'has a secret ritual before every performance',

  'would happily attend their own funeral',
  'believes they were a villain in a past life',
  'considers a Ouija board a party game',
  'could survive a horror movie with their sarcasm alone',

  'has a favorite apocalypse scenario',

  'could win a staring contest with the Grim Reaper',

  'would replace their morning coffee with a potion from a witch',

  'believes their spirit animal is a sloth on a caffeine high',
  'thinks laughter is just a side effect of not crying',
  'would use a time machine to procrastinate more efficiently',
  'considers their morning coffee as a personality trait',

  'has a hidden talent for underwater basket weaving',
  'thinks sarcasm should be an Olympic sport',
  'considers their life a series of unfortunate naps',
  'believes they were a cat in a past life, hence the attitude',
  'thinks Mondays should be considered a crime against humanity',

  'would want the ability to teleport, but only to avoid small talk',
  `has a master's degree in "avoiding responsibilities"`,
  'believes their soulmate is a Wi-Fi connection',

  'is fluent in at least three languages: sarcasm, irony, and satire',
  'believes they can read minds but prefers not to',
  `thinks if life was a video game, they'd be stuck on the tutorial level`,
  'believes they are the human embodiment of a meme',

  'has a secret plan to replace world leaders with trained penguins',
  'thinks they could survive a day without technology, but why risk it',
  'considers their life motto to be "expect the unexpected, but still be surprised"',

  'believes the best way to avoid mistakes is to not do anything, ever',
  'thinks a well-timed eye roll is a valid form of communication',
  'considers themselves a connoisseur of passive-aggression',

  'thinks the world would be a better place if everyone wore capes',
  'has a plan to replace all cars with roller-skates',
  'believes they could create a new language using only emojis',

  `thinks they have a superpower but won't tell anyone what it is`,
  `always breaks into spontaneous dance in public`,
  `creates elaborate sandcastles in their living room`,
  `writes love letters to their favorite food`,
  `thinks they are a long-lost member of royalty`,
  `believes they can control the weather with their mind`,
  `sings to their food before they eat it`,
  `moonwalks instead of walking forwards`,
  `has a tattoo of their favorite cartoon character`,
  `thinks they are a ninja but is terrible at hiding`,
  `throws surprise parties for random strangers`,
  `has a secret shrine dedicated to their favorite celebrity`,
  `believes they have a twin living in a parallel universe`,
  `wants to become a professional whistler`,
  `thinks they are a time traveler stuck in the wrong era`,
  `claims to have invented a new color`,
  `gives motivational speeches to their mirror every morning`,
  `wants to turn their car into a submarine`,
  `is on a quest to find the perfect ice cream flavor`,

  `believes dumbbells are the ultimate fashion accessory`,
  `wants to open a gym-themed restaurant`,
  `thinks push-ups are the solution to any problem`,
  `tries to code an app that makes decisions for them`,
  `thinks in binary while daydreaming`,
  `conducts team-building exercises during their dreams`,
  `gives motivational speeches to their pets`,
  `dreams of creating a work-themed amusement park`,
  `turns every conversation into a status update`,
  `meditates to the sound of a conference call`,
  `uses a spreadsheet to plan their vacations`,
  `tries to implement a dress code for their social circle`,
  `talks to every stranger they meet`,
  `starts a new club or group every week`,
  `creates a secret language only they understand`,
  `spends their weekends organizing their book collection`,
  `perfects the art of disappearing at social gatherings`,
  `invents a new board game every month`,
  `wears a clown nose to serious meetings`,
  `laughs at their own jokes before they tell them`,
  `lives by the motto "no rules, just fun"`,
  `constantly seeks adrenaline-pumping adventures`,
  `wants to move into a treehouse`,
  `dreams of hiking every mountain on Earth`,
  `turns every household item into a DIY project`,
  `believes duct tape can fix anything`,
  `builds their own furniture from scratch`,
  `has a dedicated room for football memorabilia`,
  `tries to incorporate football into every conversation`,
  `meditates during roller coaster rides`,
  `remains calm even when their ice cream falls to the ground`,
  `writes a self-help book on the art of unflappability`,

  `reads encyclopedias for fun`,
  `analyzes the deeper meaning of every joke they hear`,
  `considers chess a thrilling pastime`,
  `meticulously plans every minute of their day`,
];

export { VOTE_QUESTIONS };
