const VOTE_QUESTIONS = [
  'needs a hug',
  'is thinking about sausage right now',
  'is thinking about a unicorn right now',
  'is up at 7am on a Sunday',
  'would eat off the floor without thinking twice',
  'got too much Red Bull as a child',
  'has never experienced true anger',
  'thinks they could take on a lion with their bare hands',
  'is always overdressed',
  'can be a bit of a pretentious snob',
  'is a bit of a perfectionist',
  'would ask to speak to the manager',
  'would happily listen to one song for the rest of their life',
  'is a turtle',
  'will still just not get it in 10 years',
  'could be the boss',
  'has the most misunderstood humour',
  'will be totally different in 10 minutes',
  'should be sent to a distant planet',
  'has a secret treasure chest',
  'gives awful hugs',
  'gives great hugs',
  'would you never want as your backup if shit went down',
  'would try to fix the titanic with super glue',
  'would make a good ninja',
  'should we all hug right now',
  'would bring a knife to a fistfight',
  'never has an off day',
  'has too many secrets',
  'looks different to their personality',
  'will still be there for us 10 years',
  'thinks they are a professional athlete',
  'would make a good priest',
  'knows all the words to every ABBA song',
  'needs to see a fashion guru',
  'would you like to go club with',
  'is harbouring negative feelings',
  'is always underdressed',
  'is ready to shake things up',
  'would make a great surfer',
  "didn't get enough discipline as a child",
  'is going to complain at a restaurant',
  'is the one making silly suggestions in meetings',
  'would you like to go on a road trip with',
  "isn't hungry but is still ordering for two",
  'needs to be slapped out of it',
  'thinks they are good looking',
  'reckons they are an artist',
  'will lie to get themselves out of any situation',
  'needs to take a chill pill',
  'is hiding someone in their basement',
  'is hiding their true intelligence',
  'would make a good referee',
  'has delusions of greatness',
  'is still hungover from last night',
  'knows the meaning of life',
  'deserves a high five',
  'needs a shot of tequila',
  'thinks they are the boss',
  'eats too much avocado',
  'does all their shopping online',
  'would make a great public speaker',
  'would make a great therapist',
  'has got moves on the dance floor',
  'is unreasonably cheerful',
  'is a smooth talker',
  "doesn't know their true power",
  'needs to wake up',
  'would make a good negotiator',
  'believes in aliens',
  'is waiting for the right time to poison everyone',
  'eats pizza, crust first',
  'is really a vampire',
  'still gets Happy Meals from McDonalds',
  'gets a nosebleed if they walk too fast',
  'needs a few years in prison',
  'needs to get a haircut',
  'has a bad habit of not taking their medication',
  'has the wildest dreams',
  'is thinking about fairies right now',
  'will thrive in a zombie apocalypse',
  'is really a scientologist',
  'is going to live long enough to see themselves become the villain',
  'is most likely to be a spy',
  'will we still remember in 20-years time',
  'is planning their escape',
  'should narrate a nature documentary',
  `do you want as your "hype man"`,
  'is always the bad cop',
  'is always the good cop',
  'is visiting us from the future',
  'still believes in Santa',
  'will we send when the gods demand a sacrifice',
  'makes us laugh unintentionally',
  'watches too much Netflix',
  `would make a good farmer`,
  `drives a tractor`,
  `is definitely a morning person`,
  `is going to be famous`,
  `watches Home Alone in the summer`,
  `has a podcast`,
  `would rather get lost than ask for directions`,
  `cries during movies`,
  `is most likely to start a food fight`,
  `will betray you when you least expect it`,
  `is giving you dodgy advice`,
  `makes you feel warm and cuddly`,
  `drives too fast`,
  `was spoilt as a child`,
  `knows the real truth`,
  `would make a good car salesman`,
  `has 3 nipples`,
  `has the best pornstar name`,
  `is still searching for freedom`,
  `is going to be a great chef`,
  `is going to leave this world on a horse`,
  `uses a lot of sarcasm`,
  `has to be at every party`,
  `would make a great mix playlist`,
  `is going to leave us`,
  `pretends not to know you`,
  `makes you think`,
  `likes bad TV`,
  `should be a poet`,
  `loves gardening`,
  `is too real for this world`,
  `would make a good sex therapist`,
  `is going to write the next Bond movie`,
  `is shy around new people`,
  `is intimidated by life`,
  `loves catching bad guys`,
  `loves to drive fast cars`,
  `would make a great neighbour`,
  `uses an axe as a doorstop`,
  `shy of everyone and in love with nobody`,
  `digs holes`,
  `talks in their sleep`,
  `is a world class karaoke singer`,
  `never loses a fight`,
  `loves to scream`,
  `makes the best spaghetti and meatballs`,
  `runs a pet adoption centre`,
  `is a hippie at heart`,
  `is trying to live forever`,
  `cries at the hairdresser every time they cut it too short`,
  `can never say no`,
  `says they're vegan but buys burgers`,
  `has a librarian as a parent`,
  `needs an advice from their friend`,
  `cannot stand stupid people`,
  `would be the first person to shout at you when you drop your phone`,
  `would never let you get away with anything`,
  `is trying to make a movie about their life`,
  `is feeling something`,
  `has all the self control of a baby`,
  `hates reality`,
  `dreads mowing the lawn`,
  `would love being famous`,
  `would be the first one to run away with you`,
  `is going to get eaten by a bear`,
  `will laugh at your sadness`,
  `loves trashy television`,
  `loves to talk about themselves in third person`,
  `cries in front of your house every time they leave`,
  `hates wearing clothes`,
  `loves the colour purple`,
  `constantly trying to fix something or someone that isn't broken`,
  `is too trusting`,
  `wants you to dance for them and keeps saying that there's no better time than now`,
  `is convinced they are the one`,
  `would put hot sauce in your iced tea`,
  `blames everything on a conspiracy`,
  `has an imaginary friend`,
  `would spend one night a week at your place`,
];

export { VOTE_QUESTIONS };